<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
 
 use Doctrine\ORM\EntityRepository;
 
class UserRepository extends \Doctrine\ORM\EntityRepository
{
}
